// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaJNeHXBh49zHoWtfuzDSmns0wnu5a3cY',
    appId: '1:127975888177:web:886e64d3a2cacdf86b8c10',
    messagingSenderId: '127975888177',
    projectId: 'yummy-market-366f1',
    authDomain: 'yummy-market-366f1.firebaseapp.com',
    storageBucket: 'yummy-market-366f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLroDgRSnXKgkFOInV2bnFxz2clE3stm8',
    appId: '1:127975888177:android:6c3bace8fa8719936b8c10',
    messagingSenderId: '127975888177',
    projectId: 'yummy-market-366f1',
    storageBucket: 'yummy-market-366f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDujbySxYvtDkSuTWle-nUHBCLVgyaMVQU',
    appId: '1:127975888177:ios:25126a3fffa1265e6b8c10',
    messagingSenderId: '127975888177',
    projectId: 'yummy-market-366f1',
    storageBucket: 'yummy-market-366f1.firebasestorage.app',
    iosBundleId: 'com.example.yummyMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDujbySxYvtDkSuTWle-nUHBCLVgyaMVQU',
    appId: '1:127975888177:ios:25126a3fffa1265e6b8c10',
    messagingSenderId: '127975888177',
    projectId: 'yummy-market-366f1',
    storageBucket: 'yummy-market-366f1.firebasestorage.app',
    iosBundleId: 'com.example.yummyMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaJNeHXBh49zHoWtfuzDSmns0wnu5a3cY',
    appId: '1:127975888177:web:baae021edb8a240b6b8c10',
    messagingSenderId: '127975888177',
    projectId: 'yummy-market-366f1',
    authDomain: 'yummy-market-366f1.firebaseapp.com',
    storageBucket: 'yummy-market-366f1.firebasestorage.app',
  );
}
